/*
 * Beat Heart Server
 * Beat Heart documentation for communication between server and client
 *
 * OpenAPI spec version: 0.1
 * Contact: server@beatheart.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.ceg.med.beatheartfactory.client.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * Activity
 */
public class Activity implements Parcelable, Serializable {
    private static final long serialVersionUID = 1L;

    @SerializedName("duration")
    private Integer duration = null;

    @SerializedName("actionType")
    private String actionType = null;

    public Activity duration(Integer duration) {
        this.duration = duration;
        return this;
    }

    /**
     * Get duration
     *
     * @return duration
     **/
    @ApiModelProperty(value = "")
    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public Activity actionType(String actionType) {
        this.actionType = actionType;
        return this;
    }

    /**
     * Get actionType
     *
     * @return actionType
     **/
    @ApiModelProperty(value = "")
    public String getActionType() {
        return actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Activity activity = (Activity) o;
        return Objects.equals(this.duration, activity.duration) &&
                Objects.equals(this.actionType, activity.actionType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(duration, actionType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Activity {\n");

        sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
        sb.append("    actionType: ").append(toIndentedString(actionType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public void writeToParcel(Parcel out, int flags) {

        out.writeValue(duration);

        out.writeValue(actionType);
    }

    public Activity() {
        super();
    }

    Activity(Parcel in) {

        duration = (Integer) in.readValue(null);
        actionType = (String) in.readValue(null);
    }

    public int describeContents() {
        return 0;
    }

    public static final Creator<Activity> CREATOR = new Creator<Activity>() {
        public Activity createFromParcel(Parcel in) {
            return new Activity(in);
        }

        public Activity[] newArray(int size) {
            return new Activity[size];
        }
    };
}

